# Generated by Django 5.1.3 on 2025-03-14 12:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_avaliacao_nota'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together={('usuario', 'jogo')},
        ),
        migrations.AddField(
            model_name='jogo',
            name='plataformas',
            field=models.ManyToManyField(to='cadastros.plataforma'),
        ),
    ]
